In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('..')
import json

In [6]:
from rlagent import QLAgent
from tokyodrift import TokyoDriftEnv, get_default_coursemap, get_driftmap

In [7]:
q = QLAgent(max_episode_len=200, gamma=1, alpha=0.1, epsilon=0.999, epsilon_shrink=0.99)

In [8]:
env = TokyoDriftEnv(get_driftmap())

In [9]:
q.fit(env, 10000)

In [10]:
import pandas as pd
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

In [173]:
env.reset()
env.render()
done = False

In [206]:

# while not done:
action = q._greedy_move(env.int_state)
print(action)
s, r, done, _ = env.step(action)
print(env.velocity)
print(s, r, done)
if env._is_wall(env.state):
    print('crash')
env.render().style.applymap(lambda x: 'background-color: red' if x == 4 else '')

0
[0 2]
3977 0 True